image: golang:latest
stages:
  - build
  - test

before_script:
  - mkdir -p /go/src/github.com/FreifunkBremen/
  - cp -R "$CI_PROJECT_DIR" "/go/src/github.com/FreifunkBremen/"
  - cd "/go/src/github.com/FreifunkBremen/$CI_PROJECT_NAME"
  - go get -d -t ./...

build-my-project:
  stage: build
  script:
    - mkdir "$CI_PROJECT_DIR/bin/"
    - go get -v github.com/FreifunkBremen/$CI_PROJECT_NAME
    - mv "/go/bin/$CI_PROJECT_NAME" "$CI_PROJECT_DIR/bin/$CI_PROJECT_NAME"
  artifacts:
    paths:
      - "bin/$CI_PROJECT_NAME"
      - config_example.conf

test-my-project:
  stage: test
  script:
    - go get github.com/client9/misspell/cmd/misspell
    - misspell -error .
    - ./.ci/check-gofmt
    - ./.ci/check-testfiles
    - go test $(go list ./... | grep -v /vendor/ | grep -v /webroot/) -v -coverprofile .testCoverage.txt
    - go tool cover -func=.testCoverage.txt
  artifacts:
    paths:
     - .testCoverage.txt


test-race-my-project:
  stage: test
  script:
    - go test -race ./...
