language: go
go:
  - tip
install:
  - go get -t github.com/FreifunkBremen/freifunkmanager/...
  - go get github.com/mattn/goveralls
  - go get "golang.org/x/tools/cmd/cover"
script:
  - ./.test-coverage
  - go install github.com/FreifunkBremen/freifunkmanager/cmd/freifunkmanager
